spec: flatprofiles
spec_version: "0.7.1"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 0.7
    search:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 0.6
      max_tokens: 2048
    refiner:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 0.6
      max_tokens: 4096
      output_tokens: 500
  default: default
