spec: flatprofiles
spec_version: "0.7.1"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 0.7
      max_tokens: 4096
    extractor:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 0.3
      max_tokens: 4096
    judge:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 1.0
      max_tokens: 4096
    judge_confirm:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 1.0
      max_tokens: 4096
    summarizer:
      provider: cerebras
      name: zai-glm-4.6
      temperature: 1.0
      max_tokens: 4096
  default: default
