spec: flatprofiles
spec_version: "0.8.3"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.9
      top_p: 0.95
      max_tokens: 150000
    summarizer:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.9
      top_p: 0.95
      max_tokens: 150000
    judge:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.9
      top_p: 0.95
      max_tokens: 150000
    cerebras:
  default: default
  override: default
