spec: flatprofiles
spec_version: "0.8.0"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.7
      max_tokens: 150000
    fast:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.7
      max_tokens: 150000
    extractor:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.3
      max_tokens: 150000
  default: default
