# Model profiles for coding agent
# Separate profiles allow easy model switching and tuning per agent role

spec: flatprofiles
spec_version: "0.7.3"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.7
      max_tokens: 16000

    planner:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.7
      max_tokens: 16000

    coder:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.3
      max_tokens: 16000

    reviewer:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.3
      max_tokens: 8000

  default: default
