# Model profiles for coding agent
# Separate profiles allow easy model switching and tuning per agent role

spec: flatprofiles
spec_version: "0.7.3"

data:
  model_profiles:
    default:
      provider: litellm
      name: anthropic/claude-sonnet-4-20250514
      temperature: 0.7
      max_tokens: 16000

    planner:
      provider: litellm
      name: anthropic/claude-sonnet-4-20250514
      temperature: 0.7
      max_tokens: 16000

    coder:
      provider: litellm
      name: anthropic/claude-sonnet-4-20250514
      temperature: 0.3
      max_tokens: 16000

    reviewer:
      provider: litellm
      name: anthropic/claude-sonnet-4-20250514
      temperature: 0.3
      max_tokens: 8000

  default: default
