spec: flatprofiles
spec_version: "0.7.3"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0
      max_tokens: 10000
    question_generator:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0
      max_tokens: 10000
    response_evaluator:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0
      max_tokens: 10000
    feedback_provider:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0
      max_tokens: 10000
  default: default
