spec: flatprofiles
spec_version: "2.0.0"

data:
  model_profiles:
    default:
      provider: openrouter/z-ai
      name: glm-4.7
      temperature: 1.0
      max_tokens: 10000
    question_generator:
      provider: openrouter/z-ai
      name: glm-4.7
      temperature: 1.0
      max_tokens: 10000
    response_evaluator:
      provider: openrouter/z-ai
      name: glm-4.7
      temperature: 1.0
      max_tokens: 10000
    feedback_provider:
      provider: openrouter/z-ai
      name: glm-4.7
      temperature: 1.0
      max_tokens: 10000
  default: default
