spec: flatprofiles
spec_version: "0.8.0"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.7
    analyzer:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0
      max_tokens: 4096
      output_tokens: 600
    writer:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.6
      max_tokens: 8192
      output_tokens: 2000
    checker:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0
      max_tokens: 4096
      output_tokens: 800
    fixer:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.6
      max_tokens: 8192
      output_tokens: 2000
  default: default
